### ISSUE TITLE
Review Wrapper section in landing page #04

### ISSUE THREAD

**Issue by Anggayudhaprst** [ArdyYusuf-AgriTech/React-Bookbuzz#24]
including 3 reviewer dengan sliding with same background

**Comment by ArdyYusuf-AgriTech** [comment]
- [ ] Banner Wrapper

- [ ] Catergory wrapper
- [ ] feature product wrapper

- [ ] product wrapper
- [ ] shipping desc wrapper
- [ ] subscribe wrapper

**Comment by ArdyYusuf-AgriTech** [comment]
sudah di up, sliding dengan timer bukan dengan button

mohon di review
